### ISSUE TITLE
Publish latest version to npm

### ISSUE THREAD

**Issue by Maks9** [csstools/postcss-advanced-variables#104]
Please publish latest version 4.0.0 to npm.
Current npm version is 3.0.1

**Comment by romainmenke** [comment]
Done 🚀 

<img width="386" alt="Screenshot 2024-03-10 at 16 53 33" src="https://github.com/csstools/postcss-advanced-variables/assets/11521496/eebd3bab-e2be-48d7-8d39-f69db5728f46">
