### ISSUE TITLE
Upgrading to 4.0.0 stops resolving variables

### ISSUE THREAD

**Issue by ashil88** [csstools/postcss-advanced-variables#108]
Hi

After upgrading the v4.0.0 our variables are no longer being resolved/preserved. I can't see any missed changes at our end having looked at the changelog, so not sure what the issue is... when I revert back to be v3 the variables are resolved/preserved as expected.

These are the other postcss plugins also being used if it helps at all:

```
postcssPresetEnv = require('postcss-preset-env'),
postcssAdvancedVars = require('postcss-advanced-variables'),
postcssCalc = require('postcss-calc'),
postcssCustomMedia = require('postcss-custom-media'),
postcssCustomProperties = require('postcss-custom-properties'),
postcssMediaMinMax = require('postcss-media-minmax'),
postcssNesting = require('postcss-nesting'),
postcssNested = require('postcss-nested')
```

Thanks
Ashil

**Comment by romainmenke** [comment]
Hi @ashil88,

Can you make a minimal reproduction?

A GitHub repro with only the relevant code that worked with v3 and fails with v4?

I don't know what you mean with `our variables are no longer being resolved/preserved`.
I need to know exactly what is happening and what you expected instead.

**Comment by romainmenke** [comment]
@ashil88 

I just ran some tests and everything just works.
Closing this for now.

Happy to re-open if you can provide a minimal reproduction.
