### ISSUE TITLE
importPaths option is not useful due to upstream bug in sass resolver

### ISSUE THREAD

**Issue by chriszarate** [csstools/postcss-advanced-variables#74]
The `sass-import-resolve` has a bug that resolves its promise with `undefined`, which causes a destructuring error:

```
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'file' of undefined
  at node_modules/postcss-advanced-variables/index.bundle.js:400:21
```

https://github.com/jonathantneal/sass-import-resolve/pull/2

**Comment by romainmenke** [comment]
Closing because this is an upstream issue.
