### ISSUE TITLE
Global declarations

### ISSUE THREAD

**Issue by jods4** [csstools/postcss-advanced-variables#90]
Currently the `variables` option allows you to have a global list of variables (e.g. from JS or JSON).

It would be nice if that feature was extended to support a CSS filename, which would be prepended as an `@import` to all other CSS files.

This way would support sharing other declarations such as `@mixin` and not just `$variables`.

**Comment by tbredin** [comment]
With sass I have used [this plugin](https://www.npmjs.com/package/nuxt-sass-resources-loader) to provide a set of global resources to all of my sass blocks, whether they're in a scss file or in my single file components. I agree it would be great to add this as a feature.

**Comment by romainmenke** [comment]
This is possible with the generic plugin : https://github.com/csstools/postcss-plugins/tree/main/plugins/postcss-global-data#readme
