### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by ALMaclaine** [csstools/postcss-advanced-variables#94]
Can a new version be published please?

**Comment by mweber06** [comment]
It's getting close to a year since the PostCSS 8 fork and with Nuxt 3 moving to version 8, Sass is looking more and more appealing having advanced variables working today.

**Comment by mweber06** [comment]
I see, the fork was published, strange way to update a package.

**Comment by juanca** [comment]
Where is the latest published? I only see up to 3.0.1 at https://www.npmjs.com/package/postcss-advanced-variables I am looking for ^4

**Comment by lexich-writer** [comment]
+1

**Comment by X-Tender** [comment]
Looks like its not published yet to npm. Or is there any other way how to use it in my project?

**Comment by ALMaclaine** [comment]
Things that are never happening:

This package getting published.

I feel really bad for @jonathantneal that his life is so busy he doesn't have 5 minutes to publish a package.

We abandoned the postcss ecosystem because of nonesense like this.
